### ISSUE TITLE
Spam entry in http://misoproject.com/d3-chart/charts.html

### ISSUE THREAD

**Issue by konstantinmagg** [misoproject/d3.chart#120]
Hi there,

not sure, if this is the right place for this. If there is a better way to address this, please let me know.

Seems you had a spam bot comming through at [http://misoproject.com/d3-chart/charts.html](http://misoproject.com/d3-chart/charts.html):

> Fake Ray Bans
> `http://allraybansunglasses.com`
> This is deficient in several characteristic and for that reason new iphone 4 have.. nonetheless it is hotselling unit.. Constantly hang on to get the on the job apple ipad...
> . -= Severe Agrawal's final weblog... a couple of Free apple ipad Purposes intended for People =-.

If it was my page, I'd delete this entry.

Hope this could help.

**Comment by andreas-marschke** [comment]
Hey @konstantinmagg ! 

Checked code:
It's fetched from a google spreadsheet: https://github.com/misoproject/misoproject.github.io/blob/dev/src/partials/d3-chart/_contribchart.haml

Which is referenced here:
https://github.com/misoproject/misoproject.github.io/blob/dev/src/pages/d3-chart/charts.haml

At best someone from the Miso Project (@iros @jugglinmike ?) should have a look and curate which of the submissions is an actual chart and which is just spam.

If Google Forms has the option to support Captcha or a similar validation that it's not a robot that would help too.

**Comment by iros** [comment]
Just removed it. Thanks!!

**Comment by iros** [comment]
Great catch! Just cleared that one. Thanks for the heads up.

Irene Ros
Director of Data Visualization, Bocoup, http://bocoup.com/datavis
Organizer and Program Chair, OpenVis Conf, http://openvisconf.com
irene@bocoup.com
